baseURL = "/"
languageCode = "en"
title = "Ranting Robert"
theme = "hugo-nuo"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true

# Disqus Username
disqusShortname = "robertlunderwood"

# Google Analytics UA number
googleAnalytics = "UA-112526881-1"

# Copyright of your post
copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License，please give source if you likes to quote or reproduce."

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "http://www.robertlunderwood.com"

[[menu.main]]
  name = "About Me"
  weight = 2
  identifier = "About"
  url = "http://www.robertlunderwood.com/about"

[[menu.main]]
  name = "Resume"
  weight = 3
  identifier = "Resume"
  url = "http://www.robertlunderwood.com/resume"
  
[[menu.main]]
  name = "Ranting Robert"
  weight = 4
  identifier = "Ranting Robert"
  url = "/"
  
[[menu.main]]
  name = "About Ranting Robert"
  weight = 5
  identifier = "About Ranting Robert"
  url = "/about-ranting-robert"

# Add your own params here
[params]
  author = "Robert Underwood"
  avatar = "/img/img_0010.jpg"
  seotitle = "Ranting Robert"
  subtitle = "Keeping it Real"
  description = "This page is for all of my rants and thoughts about a lot of things.  If there is something you want me to talk about, let me know."
  paginate = 10
  addThis = "ra-5a63939b44fe33a3"

  # Choose your social networks
  email = "rlu@robertlunderwood.com"
  #github = "github_username"
  twitter = "robunderwood"
  linkedin = "robertlunderwood"
  # weibo = "weibo_username"
  # wechat= "/img/qrcode.jpg" # Replace with your wechat qrcode image
  facebook = "robertlunderwood"
  google = "+robertunderwood"
  # instagram = "instagram_username"
  youtube = "robertlunderwood"
  # vimeo = "vimeo_username"
  # medium = "medium_username"
  # quora = "quora_username"
  # pinterest = "pinterest_username"
  # dribbble = "dribbble_username"
  # behance = "behance_username"
  # jsfiddle = "jsfiddle_username"
  # codepen = "codepen_username"
  # zhihu = "zhihu_username"
  # douban = "douban_username"
  # bilibili = "bilibili_id_number"

  # Changyan Comments (China Only)
  # changyan = false
  # changyanId = "cyt3toRiB"
  # changyanConf = "prod_0908b1cb9a581501753cce1ed074dbe3"

  # Google Webmaster
  # https://www.google.com/webmasters/
 # googleSiteVerification = "_moDmnnBNVLBN1rzNxyGUGdPHE20YgbmrtzLIbxaWFc"

  # Bing Webmaster
  # https://www.bing.com/toolbox/webmaster/
  # msValidate = "22596E34341DD1D17D6022C44647E587"

  # Baidu Webmaster (China Only)
  # https://zhanzhang.baidu.com/
  # baiduSiteVerification = "MZ23SPxxfa"

  # Sogou Webmaster (China Only)
  # http://zhanzhang.sogou.com/
  # sogouSiteVerification = "m2jktMQTZm"

  # 360 Webmaster (China Only)
  # http://zhanzhang.so.com/
  # soSiteVerification = "b7ab3b4c2edbc856642004d1b8c27a91"

  # Baidu Tongji (China Only)
  # https://tongji.baidu.com/
  # baiduTongji = "e21dc1e8a592188271b615159dc88af7"

  # ICP Number (China Only)
  # ICP = "苏ICP备16005986号-2"
